### ISSUE TITLE
Stuck, not smooth

### ISSUE THREAD

**Issue by jijkbird** [mo-ah-dawood/ready#10]
1.5.9+11 version is very stuck, and the slide, click and animation are stuck, not smooth. Have tried release and debug

**Comment by jijkbird** [comment]
https://user-images.githubusercontent.com/20245625/222949095-8b784e63-a665-4189-a439-f49224e1e39c.mp4

release mode

**Comment by mu-dawood** [comment]
can you please confirm if this is still persist in 1.5.9+12

**Comment by mu-dawood** [comment]
and please see the demo https://ready-19c04.web.app/#/

**Comment by jijkbird** [comment]
Much smoother
