### ISSUE TITLE
The Scrollbar's ScrollController has no ScrollPosition attached.

### ISSUE THREAD

**Issue by jijkbird** [mo-ah-dawood/ready#11]
════════ Exception caught by animation library ═════════════════════════════════
The following assertion was thrown while notifying status listeners for AnimationController:
The Scrollbar's ScrollController has no ScrollPosition attached.

A Scrollbar cannot be painted without a ScrollPosition.

The Scrollbar attempted to use the PrimaryScrollController. This ScrollController should be associated with the ScrollView that the Scrollbar is being applied to.A ScrollView with an Axis.vertical ScrollDirection on mobile platforms will automatically use the PrimaryScrollController if the user has not provided a ScrollController. To use the PrimaryScrollController explicitly, set ScrollView.primary to true for the Scrollable widget.

When the exception was thrown, this was the stack
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
packages/flutter/src/widgets/scrollbar.dart 1597:9                                <fn>
packages/flutter/src/widgets/scrollbar.dart 1621:14                               [_debugCheckHasValidScrollPosition]
packages/flutter/src/widgets/scrollbar.dart 1564:14                               [_validateInteractions]
packages/flutter/src/animation/listener_helpers.dart 240:19                       notifyStatusListeners
packages/flutter/src/animation/animation_controller.dart 822:7                    [_checkStatusChanged]
packages/flutter/src/animation/animation_controller.dart 756:5                    [_startSimulation]
packages/flutter/src/animation/animation_controller.dart 619:12                   [_animateToInternal]
packages/flutter/src/animation/animation_controller.dart 467:12                   forward
packages/flutter/src/widgets/scrollbar.dart 1973:37                               [_handleScrollNotification]
packages/flutter/src/widgets/notification_listener.dart 130:22                    onNotification
packages/flutter/src/widgets/framework.dart 3170:18                               dispatchNotification
packages/flutter/src/widgets/framework.dart 3173:13                               dispatchNotification
packages/flutter/src/widgets/framework.dart 4534:24                               dispatchNotification
packages/flutter/src/widgets/notification_listener.dart 60:13                     dispatch
packages/flutter/src/widgets/scroll_activity.dart 92:90                           dispatchScrollUpdateNotification
packages/flutter/src/widgets/scroll_position.dart 912:5                           didUpdateScrollPositionBy
packages/flutter/src/widgets/scroll_position_with_single_context.dart 233:7       pointerScroll
packages/flutter/src/widgets/scrollable.dart 793:16                               [_handlePointerScroll]
packages/flutter/src/gestures/pointer_signal_resolver.dart 90:7                   resolve
packages/flutter/src/gestures/binding.dart 466:29                                 handleEvent
packages/flutter/src/gestures/binding.dart 440:14                                 dispatchEvent
packages/flutter/src/rendering/binding.dart 336:11                                dispatchEvent
packages/flutter/src/gestures/binding.dart 395:7                                  [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 357:5                                  handlePointerEvent
packages/flutter/src/gestures/binding.dart 314:7                                  [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 295:7                                  [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1183:13                               invoke1
lib/_engine/engine/platform_dispatcher.dart 243:5                                 invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 156:39                                    [_onPointerData]
lib/_engine/engine/pointer_binding.dart 393:14                                    [_handleWheelEvent]
lib/_engine/engine/pointer_binding.dart 708:7                                     <fn>
lib/_engine/engine/pointer_binding.dart 383:43                                    <fn>
lib/_engine/engine/pointer_binding.dart 212:80                                    <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 367:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 372:39  dcall
The AnimationController notifying status listeners was: AnimationController#2f5ea(▶ 0.000)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
The Scrollbar's ScrollController has no ScrollPosition attached.
════════════════════════════════════════════════════════════════════════════════

**Comment by jijkbird** [comment]
ready: ^1.5.9+12

**Comment by mu-dawood** [comment]
Can you fill the code to see what happen

**Comment by mu-dawood** [comment]
Ok fixed `1.5.9+15` and thank you very much
