### ISSUE TITLE
Error while using ReadyDashboard

### ISSUE THREAD

**Issue by Murali-Learner** [mo-ah-dawood/ready#14]
```
import 'package:flutter/material.dart';
import 'package:ready/ready.dart';

class DashBoardExample extends StatelessWidget {
  const DashBoardExample({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ReadyDashboard(items: [
      DashboardItem(
          label: "Icons",
          id: "responsive",
          builder: (parameters) {
            return Text("${parameters.keys}");
          },
          icon: Icon(Icons.menu)),
      DashboardItem(
          label: "ITemss",
          id: "data",
          builder: (parameters) {
            return Text("prams ${parameters.values}");
          },
          icon: Icon(Icons.food_bank)),
    ]);
  }
}

```

this is the code that I'm using 
it's showing this error:
: **Error: The method 'SubmenuButton' isn't defined for the class '__ResponsiveDataTableState<T, TController>'.
responsive_data_table.dart:189
- '__ResponsiveDataTableState' is from 'package:ready/src/responsive_data_table/responsive_data_table.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/ready-1.6.0/lib/src/responsive_data_table/responsive_data_table.dart').
responsive_data_table.dart:1
Try correcting the name to the name of an existing method, or defining a method named 'SubmenuButton'.
        rActions.add(SubmenuButton(
                     ^^^^^^^^^^^^^
: Error: The method 'MenuBar' isn't defined for the class '__ResponsiveDataTableState<T, TController>'.
responsive_data_table.dart:196
- '__ResponsiveDataTableState' is from 'package:ready/src/responsive_data_table/responsive_data_table.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/ready-1.6.0/lib/src/responsive_data_table/responsive_data_table.dart').
responsive_data_table.dart:1
Try correcting the name to the name of an existing method, or defining a method named 'MenuBar'.
      cells.add(MenuBar(
                ^^^^^^^

: Error: The method 'MenuStyle' isn't defined for the class '__ResponsiveDataTableState<T, TController>'.
responsive_data_table.dart:197
- '__ResponsiveDataTableState' is from 'package:ready/src/responsive_data_table/responsive_data_table.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/ready-1.6.0/lib/src/responsive_data_table/responsive_data_table.dart').
responsive_data_table.dart:1
Try correcting the name to the name of an existing method, or defining a method named 'MenuStyle'.
        style: MenuStyle(

               ^^^^^^^^^
: Error: Member not found: 'PageStorage.maybeOf'.
custom_data_table.dart:185
        PageStorage.maybeOf(context)?.readState(context) as int? ?? 0;
                    ^^^^^^^
: Error: The method 'MenuItemButton' isn't defined for the class '_LoadingButtonState'.
loading_button.dart:56
- '_LoadingButtonState' is from 'package:ready/src/responsive_data_table/responsive_data_table.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/ready-1.6.0/lib/src/responsive_data_table/responsive_data_table.dart').
responsive_data_table.dart:1
Try correcting the name to the name of an existing method, or defining a method named 'MenuItemButton'.
      return MenuItemButton(

             ^^^^^^^^^^^^^^
Failed to compile application.**

**Comment by mu-dawood** [comment]
Upgrade flutter

**Comment by Murali-Learner** [comment]
Can't I use this package on flutter 3.3.6?

**Comment by mu-dawood** [comment]
you can use older version of this package before 1.5
