### ISSUE TITLE
Update to intl 0.18.0

### ISSUE THREAD

**Issue by andyakendegue** [mo-ah-dawood/ready#4]
Hi Mohamed.
Congratulations on making this great plugin. I saw it this morning on LinkedIn and it was a good news for me stucking with form validations. 
But when i tried to integrate to my code with intl 0.18.0 it didn't install.
So is it possible to upgrade the plugin to use intl 0.18.0 ?

Thank you in advance !

**Comment by mu-dawood** [comment]
thanks for your comment

all ready packages are updated to intl 18

pls use ready validation: 2.3.0
