### ISSUE TITLE
The method 'SubmenuButton' isn't defined for the type '__ResponsiveDataTableState'.

### ISSUE THREAD

**Issue by jijkbird** [mo-ah-dawood/ready#5]
The method 'SubmenuButton' isn't defined for the type '__ResponsiveDataTableState'.

The method 'MenuBar' isn't defined for the type '__ResponsiveDataTableState'.

The method 'MenuItemButton' isn't defined for the type '_LoadingButtonState'.

**Comment by jijkbird** [comment]
@mo-ah-dawood

**Comment by jijkbird** [comment]
no main.dart

**Comment by mu-dawood** [comment]
MenuBar is new widget In flutter 3.7.0
So you need to update your flutter or use older version of this package

**Comment by jijkbird** [comment]
@mo-ah-dawood thanks,it's working
